POST http://localhost:9091/addTicket
Accept: application/json
Content-Type: application/json



{

  "titre": "Tests",
  "anomalie": {
    "refAnomalie": "33254f69-c8ad-4f19-abfb-57fb0d508b36"
  },
  "casDeTest": {
    "refCasTest": "ac9a2cc6-4d8b-4bc0-91da-f5a7fd6082c0"
  }
}